 ## Pandas Introduction and other basic operations

In [2]:
import pandas as pd

df = pd.read_csv('random.csv')
newDf = df[['name']] # extracting specific columns from df (dataframe)
newDf.head()
newDf.index = ['a','b','c','d','e'] # changing index from integer to letters.
newDf.head()

            name
a    Alice Smith
b      Bob Jones
c  Charlie Brown
d   Diana Prince
e    Evan Wright

In [7]:
newestDf = df.loc[0:1, 'id':'department'] # this is used to slice a specific part of the table. Usefull when we know exactly what data we need
newestDf.head()

    id         name   department
0  101  Alice Smith  Engineering
1  102    Bob Jones    Marketing